config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api do
    resources :users do
      collection do
        post 'login', to: 'users#login'
        post 'register', to: 'users#register'
        get 'test', to: 'users#test'
      end
    end
  end

  namespace :admin do
    resources :admin

    resources :film do
      member do
        get 'crawl', to: 'film#crawl'
      end

      collection do
        get 'crawl_all', to: 'film#crawl_all'
      end
    end

  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :film
end

app/models/episode.rb
class Episode < ApplicationRecord

end

app/models/film.rb
class Film < ApplicationRecord
  has_many :seasons
  has_many :comments
  has_and_belongs_to_many :genres
end

app/models/film_genre.rb
class FilmGenre < ApplicationRecord
  belongs_to :film
  belongs_to :genre
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_and_belongs_to_many :films
end

app/models/season.rb
class Season < ApplicationRecord
  belongs_to :film
  has_many :episodes
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password(options={validations:false})
  validates :user_name, length: {in: 6..12, message: "Tài khoản bắt buộc có 6 đến 12 ký tự"}
  validates :name, length: {minimum: 4, message: "Họ tên bắt buộc tối thiểu có 4 ký tự"}
  validates :email, format: { with: /\A\w+[\+\.\w-]*@([\w-]+\.)*\w+[\w-]*\.([a-z]{2,4}|\d+)\z/i, message: "Định dạng mail không đúng" }
  validates :password ,format: { with: /\A(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,16}\z/i, message: "Mật khẩu có độ dài 8-16, ký tự thường, hoa và ký tự đặc biệt" }
  def self.checkConfirmPassword(user_param)
    msg = "Mật khẩu không trùng khớp!"
    user_param[:password] === user_param[:password_confirmation] || msg
  end
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController




end

app/controllers/admin/film_controller.rb
require 'selenium-webdriver'
require 'interactor'

class Admin::FilmController < Admin::AdminController
  layout "admin"

  def index
    @query = Film.ransack(params[:q])
    @films = @query.result(distinct: true).order(:updated_at).page(params[:page]).per(10)
  end

  def new
    @film = Film.new
  end

  def create

  end

  def show

  end

  def crawl(driver = nil, l_film = nil)
    driver = driver || Selenium::WebDriver.for(:chrome)
    film = l_film || Film.find(params[:id])
    newest_ep = Film
                    .select("films.id, MAX(episodes.index) as newest")
                    .where("films.id = ?", film.id)
                    .left_joins(seasons: :episodes)
                    .group("films.id")
                    .first
                    .newest
    index = (newest_ep || 0) + 1
    while true
      # pass episode already save
      begin
        driver.get("#{film.crawl_link}/tap-#{index}")
        sleep(2.seconds)
        # find element
        iframe = driver.find_element(:class, "player-embed")
        select = driver.find_element(:id, "season-active")
        current_ep = driver.find_element(:name, "current-episode").attribute('value')
        # break when done (url always to ep1 when index out of range)
        if ((index > 1) && current_ep.to_i == 1) || driver.current_url.include?("tap-0")
          break
        end
        # handle get data
        url = iframe.attribute("src").split("url=")[1]
        season_title = select.attribute("class").include?("hidden") ? 1 : select.find_element(:class, "season-name").text.gsub(/[^0-9]/, '')

        # save data
        season = Season.find_or_create_by(title: season_title, film_id: film.id)
        Episode.create(title: index, index: index, season_id: season.id, link: url)
      rescue
        break
      end
      index += 1
    end
  end

  def crawl_all
    driver = Selenium::WebDriver.for :chrome
    driver.get('https://vuighe.net/bang-xep-hang')
    #get top anime
    tops_anime = driver.find_elements(:class, "tray-item")
    tops_anime.each do |anime|
      film = Film.find_or_create_by(name: anime.find_element(:class, "tray-item-title").text)
      film.crawl_link = anime.find_element(:tag_name, "a").attribute("href")
      film.thumbnail = anime.find_element(:class, "tray-item-thumbnail").attribute("src")
      film.save
    end
    #every anime, go to crawl link get data
    films = Film.order(:updated_at)
    films.each do |film|
      crawl(driver, film)
    end
    redirect_to action: :index
  end

end

app/controllers/api/api_controller.rb
class Api::ApiController < ApplicationController


  def get_current_user
    @current_user = User.find_by_email request.headers["X-Bf-Email"]
  end

end

app/controllers/api/users_controller.rb
class Api::UsersController < Api::ApiController

  def register
    user = User.new(user_params)
    validate_cf = User.checkConfirmPassword(params)
    if user.valid? && validate_cf == true
      user.save
      render json: generate_user_token(user.id)
    else
      errors = user.errors.to_a || []
      errors.push(validate_cf) if validate_cf.is_a? String
      render json: errors
    end
  end

  def login
    user = User.find_by_user_name(params[:user_name])
    if user && user.user.email_token != nil && user.authenticate(params[:password])
      render json: generate_user_token(user.id)
    else
      render json: {
          msg => "Tài khoản hoặc mật khẩu không đúng"
      }
    end
  end

  def test
    @test = 'ok ne vinh'
    render 'api/users/test'
  end

  def confirm_email

  end

  def reset_password

  end

  private

  def user_params
    params.permit(:user_name, :name, :email, :password, :password_confirmation)
  end

  def generate_user_token(user)
    jwt = Auth.issue(user.id)
    jwt
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/views/admin/film/crawl.html.erb
done

app/views/admin/film/create.html.erb
new

app/views/admin/film/index.html.erb
<div class="row">
  <div class="v-form-control">
    <div class="action">
      <div class="action__title">
        <span>Danh sach phim</span>
      </div>
      <div class="action__control">
        <%= link_to new_admin_film_path, :class => "btn btn-primary btn-sm" do %>
          <svg class="icon--button">
            <use xlink:href="<%= asset_path('sprite.svg#icon-plus') %>"></use>
          </svg>
          &nbsp;<span>Thêm mới</span>
        <% end %>

        <%= link_to admin_film_index_path, :class => "btn btn-warning btn-sm" do %>
          <svg class="icon--button">
            <use xlink:href="<%= asset_path('sprite.svg#icon-spinner11') %>"></use>
          </svg>
          &nbsp;<span>Tải lại</span>
        <% end %>

        <%= link_to crawl_all_admin_film_index_path, :class => "btn btn-info btn-sm" do %>
          <svg class="icon--button">
            <use xlink:href="<%= asset_path('sprite.svg#icon-copy') %>"></use>
          </svg>
          &nbsp;<span>Crawl VuiGhe</span>
        <% end %>
      </div>
    </div>

    <div class="v-table-container">
      <table class="table table-sm text-center v-table-film">
        <thead>
        <tr>
          <th>ID</th>
          <th>Tên phim</th>
          <th>Last Update</th>
          <th>Control</th>
        </tr>
        <tbody class="table-striped">
        <% @films.each do |film| %>
          <tr>
            <td><%= film.id %></td>
            <td><%= film.name %></td>
            <td><%= film.updated_at %></td>
            <td>
              <%= link_to crawl_admin_film_path(film), :title => "Update" do %>
                <svg class="icon--button">
                  <use xlink:href="<%= asset_path('sprite.svg#icon-pencil') %>"></use>
                </svg>
              <% end %>
              <%= link_to admin_film_index_path, :title => "Chi tiết" do %>
                <svg class="icon--button">
                  <use xlink:href="<%= asset_path('sprite.svg#icon-eye') %>"></use>
                </svg>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
        </thead>
      </table>
      <%= paginate @films %>
    </div>

  </div>
</div>

app/views/admin/film/show.html.erb
show

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Film</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag 'layout', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
<div class="page__container">
  <div class="page__body">
    <div class="row">
      <div class="col-3 col-md-2">
        <div class="left-menu">
          <div class="left-menu__header">
            <div class="icon">
              <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOGwb3pB1EMZVs8L-_PtWwOHMWm28BM2k8XA&usqp=CAU">
            </div>
            <div class="text">Admin</div>
          </div>
          <div class="left-menu__body">
            <div class="left-menu__item active">
              <div class="icon">icon</div>
              <div class="text">Films</div>
            </div>
            <div class="left-menu__item">
              <div class="icon">icon</div>
              <div class="text">Blogs</div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-9 col-md-10">
        <div class="right-menu">
            <%= yield %>
        </div>
      </div>
    </div>
  </div>
</div>
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>